#!/usr/bin/env python3
"""
extract.py — migrate a monolithic menswear_spectrum.html into data/ + app/template.html.

    python3 tools/extract.py path/to/menswear_spectrum.html

Run once. After this the build is generated by build.py and the HTML is never the
source of anything. Every line that was `const NAME = <json>;` for a registered
const becomes a marker `/*@@NAME@@*/` in the template; the DATA block (multi-line
JS) is replaced the same way.
"""
import sys, os, re, json, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spec
from spec import FIELDS, BRAND_FIELDS, get, put, slug

src = sys.argv[1]
S = open(src, encoding='utf8').read()
lines = S.split('\n')

CONSTS = set(f['const'] for f in FIELDS.values() if f.get('const'))
SETTINGS = ['NOT_ASSESSED', 'STOCKED_REGION', 'REGION_NAME', 'VISIT_FORM', 'GROUPOF', 'PRICE_PASS_DATE']
CONSTS |= set(SETTINGS)

raw = {}
tmpl = []
i = 0
data_start = None
while i < len(lines):
    l = lines[i]
    m = re.match(r'^(\s*)const ([A-Z_]+)\s*=\s*(.*)$', l)
    if m and m.group(2) in CONSTS:
        indent, name, rest = m.groups()
        if name == 'DATA' and rest == '{' and data_start is None:
            # multi-line hand-written JS block; ends at the first line that is exactly "};"
            j = i
            while lines[j] != '};':
                j += 1
            block = '\n'.join(lines[i:j + 1])
            raw['DATA'] = block
            tmpl.append(f'{indent}/*@@DATA@@*/')
            data_start = i
            i = j + 1
            continue
        if rest.endswith(';'):
            body = rest[:-1]
            if body.startswith('new Set('):
                body = body[len('new Set('):-1]
            raw[name] = json.loads(body)
            tmpl.append(f'{indent}/*@@{name}@@*/')
            i += 1
            continue
    tmpl.append(l)
    i += 1

missing = CONSTS - set(raw)
if missing:
    sys.exit(f'extract: consts not found in build: {sorted(missing)}')

# ---------------------------------------------------------------- DATA rows
rows = re.findall(r'\["([^"]+)",([01]),\[([\d,\s]+)\]((?:,"[^"]*")*)\]', raw['DATA'])
band_of = {}
bands = collections.OrderedDict()
for key in ('premium', 'accessible', 'trueLux'):
    seg = raw['DATA'].split(f'{key}: {{')[1].split('brands:')[0]
    name = re.search(r'name:"([^"]*)"', seg).group(1)
    rng = re.search(r'range:"([^"]*)"', seg).group(1)
    bands[key] = {'name': name, 'range': rng}
    for r in re.findall(r'\["([^"]+)",[01],\[', raw['DATA'].split(f'{key}: {{')[1].split('\n  }')[0]):
        band_of[r] = key

recs = collections.OrderedDict()
for seat, (name, dagger, focus, extra) in enumerate(rows, 1):
    t, c, cr, st = [int(x) for x in focus.split(',')]
    rec = collections.OrderedDict()
    rec['name'] = name
    rec['band'] = band_of[name]
    rec['seat'] = seat
    rec['dagger'] = int(dagger)
    if extra:
        ex = json.loads('[' + extra[1:] + ']')
        rec['row_class'] = ex[0]
        rec['row_override'] = ex[1] if len(ex) > 1 else ''
    rec['focus'] = {'tech': t, 'comfort': c, 'craft': cr, 'style': st}
    recs[name] = rec

# ---------------------------------------------------------------- brand fields
orphans = []
for fname, f in BRAND_FIELDS.items():
    c = f['const']
    if c == 'DATA':
        continue
    obj = raw[c]
    if f['type'] == 'bool':
        for n in obj:
            if n not in recs:
                orphans.append((c, n)); continue
            put(recs[n], f['path'], True)
        continue
    if c == 'FAB':
        idx = ('denim', 'cashmere', 'linen', 'cotton', 'wool', 'synth').index(fname)
        for n, v in obj.items():
            put(recs[n], f['path'], v[idx])
        continue
    for n, v in obj.items():
        if n not in recs:
            orphans.append((c, n)); continue
        put(recs[n], f['path'], v)

# order keys in every record for readable diffs
ORDER = ['name', 'band', 'seat', 'dagger', 'row_class', 'row_override', 'focus', 'fabric', 'dials',
         'why', 'origin', 'opview', 'say', 'chan', 'conf', 'reach', 'forgc', 'forgv', 'shop',
         'onething', 'prices', 'price_checked', 'shoelink', 'notes', 'fibre',
         'doors', 'cities', 'region', 'addmen', 'addcloth']
DIAL_ORDER = ['reach', 'dur', 'forg', 'fuss', 'golffice', 'bruv', 'sail', 'shoes', 'natural'] + spec.REGISTERS
os.makedirs(spec.BRANDS, exist_ok=True)
for n, rec in recs.items():
    o = collections.OrderedDict()
    for k in ORDER:
        if k in rec:
            o[k] = rec[k]
    for k in rec:
        if k not in o:
            o[k] = rec[k]
    if 'dials' in o:
        o['dials'] = collections.OrderedDict((k, o['dials'][k]) for k in DIAL_ORDER if k in o['dials'])
    spec.save_brand(o)

spec.save_global('bands.json', bands)
spec.save_global('places.json', raw['PLACES'])
spec.save_global('changelog.json', raw['CHANGELOG'])
spec.save_global('rubric.json', raw['RUBRIC'])
spec.save_global('settings.json', collections.OrderedDict((k, raw[k]) for k in SETTINGS))

with open(os.path.join(spec.ROOT, 'app', 'template.html'), 'w', encoding='utf8') as f:
    f.write('\n'.join(tmpl))

n_slugs = len({slug(n) for n in recs})
print(f'extracted {len(recs)} brands ({n_slugs} unique slugs), {len(raw["PLACES"])} places, '
      f'{len(raw["CHANGELOG"])} changelog entries, {len(raw)} consts')
for c, n in orphans:
    print(f'ORPHAN dropped: {c} carried {n!r}, which is not a seated brand')
print(f'template  {sum(len(l)+1 for l in tmpl):,} bytes  (build was {len(S):,})')
